config/routes.rb
Rails.application.routes.draw do
  get 'user/profile'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  root 'recipes#index'
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes , through: :recipe_ingredients
  has_many :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients , through: :recipe_ingredients
	belongs_to :user # Starting with Rails 5, belongs_to relationships have a required value by default
	has_many :recipe_ingredients

 accepts_nested_attributes_for :ingredients, reject_if: proc {|attributes| attributes['name'].blank? }, allow_destroy: true 

mount_uploader :image , PlacephotoUploader

 # has_attached_file :image_url , style: {large: "600x600>", medium: "300x300>" , thumb: "150x150#" }
 # validates_attachment_content_type :image_url, content_type: /\Aimage\/.*\z/
validates :name, presence: true
validates :name, length: { minimum: 2 }
 
 def ingredients_attributes=(attributes)
self.ingredients = []
  attributes.values.each do |att|
    # binding.pry
    ingredient = Ingredient.find_or_create_by(att)
    self.ingredients<< ingredient
    end 
 end
 
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
belongs_to :recipe
belongs_to :ingredient

end
# avi
# avi.recipes => <#ARACP []>
# avi.recipes.create()

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:omniauthable
  has_many :recipes

validates :email, uniqueness: true
  def self.from_omniauth(auth)
   
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.username = auth.info.first_name
        user.password = Devise.friendly_token[0,20]

      end
  end

  def self.new_with_session(params, session)
    if session["devis.user_attributes"]
      new(session["devis.user_attributes"],without_protect: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super   
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters , if: :devise_controller?
  

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:email,:password,:remember_me])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:email,:password,:remember_me])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        # @old_user = User.find_by(email: @user.email)
        # if !@old_user
        sign_in_and_redirect @user 
        # else
        #  redirect_to new_user_registration_path,:notice => "This E-mail: #{@user.email} registered before!"
        # end
    end

    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"])
        # @old_user = User.find_by(email: @user.email)
        # if !@old_user
        sign_in_and_redirect @user
        # else
        #  redirect_to new_user_registration_path,:notice => "This E-mail: #{@user.email} registered before!"
        # end
    end

    def github
                # binding.pry

        @user = User.from_omniauth(request.env["omniauth.auth"])
        # @old_user = User.find_by(email: @user.email)
        # if !@old_user
        sign_in_and_redirect @user
        # else
        #  redirect_to new_user_registration_path,:notice => "This E-mail: #{@user.email} registered before!"
        # end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show , :edit , :update , :destroy]

  
  def index
  	@recipes=Recipe.all
  end

  def new  #get
    @recipe = current_user.recipes.build
    5.times { @recipe.ingredients.build }
  end

  def create   #POST
    # raise recipe_params.inspect
    @recipe=current_user.recipes.build(recipe_params)
    @recipe.image = params[:recipe][:image]
    if @recipe.save
      redirect_to recipe_path(@recipe) , :notice => "Your recipe was saved"
    else
      @errors = @recipe.errors.full_messages
      render "new"
    end
  end

  def show
  end

  def edit
  end

    def update
       # raise recipe_params.inspect
     if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe) , :notice => "Your recipe was Updated"
    else
      @errors = @recipe.errors.full_messages
      render "edit"
    end
  end

  def destroy 
    # raise recipe_params.inspect
    @recipe.destroy
    redirect_to recipes_path , :notice => "Your recipe #{@recipe.name} deleted"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name,:image, ingredients_attributes: [:name] )
  end

  def find_recipe
   @recipe=Recipe.find_by(id: params[:id])
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # raise params.inspect
    @user = User.find(params[:id])
    # raise @user.inspect

  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<style>
nav ul {
    list-style-type: none;
    margin: 0;
    padding-left: 5%;
    overflow: hidden;
    background-color: #337ab7;
    border-bottom: 10px;
}

nav ul li {
    float: left;
}

nav ul li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;

}

nav ul li a:hover:not(.active) {
    background-color: #a5a2a2;
}

.active {
    background-color: #064071;
}
</style>
</head>

<body>
<nav>
<ul>
 <li id="li1"><%= link_to "Home", recipes_path , id: "ac"%></li>
<% if current_user %>

  <li><%= link_to "New Recipe", new_recipe_path%></li>
  <li style="float:right"><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  <%else%>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <li><%= link_to "Sign In", new_user_session_path %></li>
  <%end%>
 
  <% if current_user %>
  <li style="float:right"><%=link_to current_user.username , edit_user_registration_path %></li>
  <%end%>

</ul>
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  
  <%= yield %>



  
</body>
</html>

app/views/recipes/_form.html.erb
<div class="middlePage">
  <%=form_for @recipe ,:html=>{:class =>'form-horizontal',:multipart => true} do |f|%>
  <fieldset>
    <legend>Create New Recipe:</legend>
    <%= f.text_field :name, autofocus: true , placeholder: "Enter Recipe Name" , id: 'textinput' ,class: 'form-control input-md'%>
    <br><br>
    <label>Main photo</label>
   <%= f.file_field :image %>

  </fieldset><br>
  <fieldset>
    <legend>Recipe Ingredients:</legend>

    <%= f.fields_for :ingredients do |ing|%>
      <%=ing.text_field :name , placeholder: "Enter Recipe Ingredient" , id: 'textinput' ,class: 'form-control input-md'%>
      <%end%>

      <!-- <div id="ingredients">
      <div><input type="text" name="name" class: 'form-control input-md'></div> 
      <a herf="#" id="add-ingredient">add more</a>
    </div>
 -->
  </fieldset>
  <br>
  <%=f.submit "Submit Recipe" , class: "btn btn-primary btn-lg btn-block"%>
  <%end%>
</div>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render partial: "form" %>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>

<div id="boxes">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <!--BOX-->
        <div class="box">
          <!--BOX HEADER-->
          <div class="box-header">
            <!--BOX TITLE-->
            <div class="box-title pull-left">
              <p><i class="fa fa-font fa-lg"></i></p>
              <p> Chef Name: <%=link_to recipe.user.username, user_path(recipe.user)%></p>
            </div>
            <!--end: TITLE-->
            <!--ICONS - FUNCTIONAL-->
            <div class="box-icon pull-right">
            <% if current_user %>
              <a href='<%=edit_recipe_path(recipe)%>' class="btn-code" title="Edit Recipe" role="button" ><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a>
              <a href='"#"' class="btn-information" title="Delete Recipe" role="button"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></a>
             <!--  <a href='<%=new_recipe_path%>' class="btn-help" title="Create New Recipe" role="button"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a> -->
              <!-- <a href='<%=recipes_path%>' class="btn-minimize" title="Refresh" role="button"><i class="fa fa-refresh fa-2x" aria-hidden="true"></i></a> -->
              <% end %>
            </div>
            
            
            <!--end: ICONS-->
          </div>
          <!--end: BOX HEADER-->
          <!--BOX CONTENT-->
          <div class="box-content">
            <div class="col-sm-4" style="float:left">
              <% if recipe.image %> 
                <%= image_tag recipe.image ,class: "img-responsive"%>
              <% else %>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
              <%end%>
              <br>
            </div>
            
            <p><%=link_to recipe.name, recipe_path(recipe)%></p>
            <p><%=recipe.description%></p>

            
          </div>
          <!--end: BOX CONTENT-->
        </div>
        <!--end: BOX-->  

      </div>
    </div>
  </div>

</div>

<%end%>

app/views/recipes/new.html.erb
<%= render partial: "form" %>

app/views/recipes/show.html.erb
<div id="boxes">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <!--BOX-->
        <div class="box">
          <!--BOX HEADER-->
          <div class="box-header">
            <!--BOX TITLE-->
            <div class="box-title pull-left">
              <p><i class="fa fa-font fa-lg"></i></p>
              <p> <%=link_to @recipe.name, recipe_path(@recipe)%></p>
            </div>
            <!--end: TITLE-->
            <!--ICONS - FUNCTIONAL-->
            <div class="box-icon pull-right">
            <% if current_user %>
              <a href='<%=edit_recipe_path(@recipe)%>' class="btn-code" title="Edit Recipe" role="button" ><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a>
              <a href='"#"' class="btn-information" title="Delete Recipe" role="button"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></a>
             <!--  <a href='<%=new_recipe_path%>' class="btn-help" title="Create New Recipe" role="button"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a> -->
              <!-- <a href='<%=recipes_path%>' class="btn-minimize" title="Refresh" role="button"><i class="fa fa-refresh fa-2x" aria-hidden="true"></i></a> -->
              <% end %>
            </div>
            
            
            <!--end: ICONS-->
          </div>
          <!--end: BOX HEADER-->
          <!--BOX CONTENT-->
          <div class="box-content">
            <div class="col-sm-4" style="float:left">
              <% if @recipe.image %> 
              <div id="h-v">
                <%= image_tag @recipe.image ,class: "img-responsive"%>
                </div>
              <% else %>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
              <%end%>
              <br>
            </div>
            
            <p><%=link_to @recipe.name, recipe_path(@recipe)%></p>
            <p><%=@recipe.description%></p>

            
          </div>

<ul class="list-group " id="clean-floating" >
  
  <%@recipe.ingredients.each do |i|%>
    <% if ! i.name.blank? %>
    <li class="list-group-item"> <%= i.name%></li>
    <%end%>
  <%end%>

</ul>
</div>
          <!--end: BOX CONTENT-->
        </div>
        <!--end: BOX-->  

      </div>
    </div>
  </div>

</div>

<!-- <div class="middlePage"> -->

app/views/users/show.html.erb
<section>

  <div class="container" style="margin-top: 30px;">
    <div class="profile-head">
      <div class="col-md- col-sm-4 col-xs-12">
        <img src="http://www.newlifefamilychiropractic.net/wp-content/uploads/2014/07/300x300.gif" class="img-responsive" />
        <h6><%= @user.username%></h6>
      </div><!--col-md-4 col-sm-4 col-xs-12 close-->


      <div class="col-md-5 col-sm-5 col-xs-12">
        <h5><%= @user.username%></h5>
        <p>Web Designer / Develpor </p>
        <ul>
          <li><span class="glyphicon glyphicon-briefcase"></span> 5 years</li>
          <li><span class="glyphicon glyphicon-map-marker"></span> U.S.A.</li>
          <li><span class="glyphicon glyphicon-home"></span> 555 street Address,toedo 43606 U.S.A.</li>
          <li><span class="glyphicon glyphicon-phone"></span> <a href="#" title="call">(+021) 956 789123</a></li>
          <li><span class="glyphicon glyphicon-envelope"></span><a href="#" title="mail"><%= @user.email%></a></li>

        </ul>


      </div><!--col-md-8 col-sm-8 col-xs-12 close-->




    </div><!--profile-head close-->
  </div><!--container close-->


  <div id="sticky" class="container">

    <!-- Nav tabs -->
    <% if current_user == @user.id %>
    <ul class="nav nav-tabs nav-menu" role="tablist">
      <li class="active">
        <a href="#profile" role="tab" data-toggle="tab">
          <i class="fa fa-male"></i> Profile
        </a>
      </li>
      <li><a href="#change" role="tab" data-toggle="tab">
        <i class="fa fa-key"></i><%= link_to "Edit Profile",edit_user_registration_path%>
      </a>
    </li>
  </ul><!--nav-tabs close-->
  <% end %>
  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane fade active in" id="profile">
      <div class="container">
        <div class="col-sm-11" style="float:left;">
          <div class="hve-pro">
            <p><%= @user.username%> is one of the most creative and accomplished chefs of our time.</p>
            </div><!--hve-pro close-->
          </div><!--col-sm-12 close-->
          <br clear="all" />
          <div class="row">
            <div class="col-md-12">
              <h4 class="pro-title"><%= @user.username%>'s Rcipes:</h4>
            </div><!--col-md-12 close-->


            <div class="col-md-6">

              <div class="table-responsive responsiv-table">
                <table class="table bio-table">
                  <tbody>
                  <% @user.recipes.each do |recipe| %>
                   <tr>      
                    <td><%= recipe.name%></td>
                    <td><%=recipe.created_at%></td> 
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div><!--table-responsive close-->
          </div><!--col-md-6 close-->